#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d II 7 8 9 0

##bspc config border_width         2
#bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

##autostart
#Polybar
$HOME/.config/bspwm/monitor.sh
#$HOME/.config/polybar/launch.sh --blocks &
$HOME/.config/polybar/launch.sh --forest &


#bspwm

bspc config border_width         0
bspc config window_gap          0

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='^4'
bspc rule -a vlc desktop='^5' follow=on
bspc rule -a mpv desktop='^5' follow=on
bspc rule -a ViberPC desktop='^6' follow=on
bspc rule -a M2011K2G state=floating follow=on
bspc rule -a Google-chrome desktop='^7' follow=on
bspc rule -a Firefox-esr desktop='^1' follow=on
bspc rule -a scrcpy state=floating follow=no
bspc rule -a Terminator state=floating

#bspc config focused_border_color "123"


# Set the border colors.
bspc config normal_border_color "$color15"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color1"
bspc config presel_feedback_color "$color1"


# move focused window to the next workspace and then switch to that workspace
#alt + shift + {Left,Right}
#    id=$(bspc query --nodes --node); bspc node --to-desktop {prev,next}; bspc desktop --focus next; bspc node --focus ${id}

